libraries:
#MOVIE LIBRARY CONFIG FOR SCHEDULED COLLECTIONS TO BE DELETED WHEN OUT OF SEASON
  Scheduled:
    library_name: Movies
    report_path: config/missing/Scheduled_report.yml
    template_variables:
      use_separator: false
    collection_files:
      - folder: /config/Scheduled/
      - pmm: year
        template_variables:
          limit: 25
          sort_by: critic_rating.desc
          data:
            starting: current_year-1
            ending: current_year-1
          summary_format: Top <<limit>> movies of <<key>>. Sorted by critic rating.
          collection_section: '010'
          schedule: range(01/01-02/01)
    settings:
      delete_not_scheduled: true
      asset_directory: config/assets

 #MAIN MOVIE LIBRARY CONFIG
  Movies:
    report_path: config/missing/Movies_report.yml
    schedule_overlays: weekly(tuesday)
    overlay_files: 
      - file: config/overlays/Top.yml
      - remove_overlays: false
    template_variables:
      use_separator: false
    collection_files:
      - folder: config/Movies/
      - pmm: decade
        template_variables:
          exclude:
          - 1960
          limit: 100
          limit_1970: 25
          summary_format: Top <<limit>> movies of the <<key>>s. Sorted by critic rating.
          summary_1970: Top <<limit_1970>> movies of the <<key>>s. Sorted by critic rating.
          minimum_items: 25
      - pmm: genre
        template_variables:
          sort_by: title.asc
          exclude:
          - Horror #IN GENRE.YML CONFIG
          - War #IN GENRE.YML CONFIG
          - Western #IN GENRE.YML CONFIG
          - Spy #IN GENRE.YML CONFIG
          - Sport #IN GENRE.YML CONFIG
          - Suspense #REMOVE IF YOU WANT INCLUDED
          - Musical #REMOVE IF YOU WANT INCLUDED
          - Indie #REMOVE IF YOU WANT INCLUDED
          - Biopic #REMOVE IF YOU WANT INCLUDED
          - Martial Arts #REMOVE IF YOU WANT INCLUDED
          - Short #REMOVE IF YOU WANT INCLUDED
        minimum_items: 10
      - pmm: imdb
        template_variables:
          use_lowest: false
          order_top: 3
          order_popular: 3
      - pmm: seasonal
        template_variables:
          emoji: ''
          schedule_independence: range(06/28-07/05)
          schedule_labor: range(09/01-09/05)
          schedule_thanksgiving: range(11/01-11/24)
          schedule_veteran: range(11/01-11/12)
          imdb_list_veteran: https://www.imdb.com/list/ls561621160/
          exclude:
          - christmas #IN HOLIDAY.YML CONFIG
          - halloween #IN HOLIDAY.YML CONFIG
          - latinx #REMOVE IF YOU WANT INCLUDED
          - disabilities #REMOVE IF YOU WANT INCLUDED
      - pmm: tautulli
        template_variables:
          use_watched: false
          list_days: 30
          list_size: 25
          list_minimum: 0
          summary_popular: A collection of the most watched movies on this Plex server.
          order_popular: 1
      - pmm: trakt
        template_variables:
          use_collected: false
          use_recommended: false
          use_watched: false
          order_popular: 4
          order_trending: 4
          schedule: weekly(monday)
      - pmm: universe
        template_variables:
          trakt_list_mcu: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe
          trakt_list_dcu: https://trakt.tv/users/lampshadetricky/lists/dc-extended-universe
          trakt_list_trek: https://trakt.tv/users/thechrisk/lists/star-trek
          trakt_list_avp: https://trakt.tv/users/thechrisk/lists/alien-predator
          minimum_items: 3
          append_data:
            star: Star Wars Saga
            trek: Star Trek Universe
            xmen: X-Men Collection
          exclude:
          - marvel #IN FRANCHISE.YML CONFIG
          - rocky #REMOVE IF YOU WANT INCLUDED
          collection_section: '106'

    operations:
      schedule: weekly(monday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: trakt_user

#4K MOVIES CONFIG
  4K Movies:
    report_path: config/missing/4K_Movies_report.yml
    schedule_overlays: weekly(tuesday)
    overlay_files:
      - file: config/overlays/Top.yml
      - pmm: resolution
        template_variables:
          use_edition: false
          use_dv: false
          use_hdr: false
          use_1080p: false
          use_720p: false
          use_576p: false
          use_480p: false
          use_1080p_hdr: false
          use_1080p_dv: false
          use_1080p_dvhdr: false
          use_1080p_plus: false
          use_720p_hdr: false
          use_720p_dv: false
          use_720p_plus: false
          use_720p_dvhdr: false
      - remove_overlays: false

    operations:
      schedule: weekly(monday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: trakt_user #SET ACCORDINGLY IF YOU DON'T USE TRAKT

#CHILDREN'S MOVIES CONFIG
  Family:
    library_name: Movies - Family
    schedule_overlays: weekly(friday)
    overlay_files:
      - file: config/overlays/Top.yml
      - remove_overlays: false
    report_path: config/missing/Kids_Movies_report.yml
    collection_files:
     #- folder: config/Kids/
      - pmm: tautulli
        template_variables:
          use_watched: false

    operations:
      schedule: weekly(friday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: trakt_user

#TV SHOWS CONFIG
  TV Shows:
    report_path: config/missing/Shows_report.yml
   #metadata_path:
   #- folder: config/Shows/
   #- file: config/Scheduled/emmy.yml
   #   template_variables:
   #     data:
   #       starting: current_year-2
   #       ending: current_year-1
    settings:
      delete_not_scheduled: true
      asset_directory: config/assets

    overlay_files:
      - remove_overlays: false
      - file: config/overlays/Top.yml

    operations:
      schedule: weekly(monday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: trakt_user

settings:
  cache: true
  cache_expiration: 30
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 1
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  save_report: true
  tvdb_language: eng
  ignore_ids: 689128,241226,762972,232618,156249,241239,71365,None,84200
  ignore_imdb_ids: tt0096548,tt0214341,tt4834232,tt0088484,tt0090509,tt0092324,tt0280249,tt4093826,tt1758429,tt0203082
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: true
  show_unconfigured: true
  playlist_exclude_users:
  run_order:
  - operations
  - metadata
  - collections
  - overlays