libraries:
#MOVIE LIBRARY CONFIG FOR SCHEDULED COLLECTIONS TO BE DELETED WHEN OUT OF SEASON
  Scheduled:
    library_name: Movies
    template_variables:
      use_separator: false
    metadata_path:
    - file: config/Scheduled/oscars.yml
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - file: config/Scheduled/golden.yml
      template_variables:
        use_year_collections: false
    - file: config/Scheduled/choice.yml
      template_variables:
        use_year_collections: false
    - file: config/Scheduled/Holiday.yml
    settings:
      delete_not_scheduled: true
 
 #MAIN MOVIE LIBRARY CONFIG
  Movies:
    template_variables:
      use_separator: false
    metadata_path:
    - folder: config/Movies/
    - pmm: tautulli
      template_variables:
        use_watched: false
    - pmm: imdb
      template_variables:
        use_lowest: false
    - pmm: genre
      template_variables:
        exclude:
        - Horror
        - War
        - Western
        - Spy
        - Sport
        sort_by: title.asc
        minimum_items: 10
    - pmm: decade
      template_variables:
        exclude:
          - 1960
        limit: 100
        limit_1970: 25
        summary_format: Top <<limit>> movies of the <<key>>s. Sorted by critic rating.
        summary_1970: Top <<limit_1970>> movies of the <<key>>s. Sorted by critic rating.
        minimum_items: 25
    - pmm: universe
      template_variables:
        trakt_list_mcu: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe
        trakt_list_dcu: https://trakt.tv/users/lampshadetricky/lists/dc-extended-universe
        trakt_list_trek: https://trakt.tv/users/thechrisk/lists/star-trek
        trakt_list_avp: https://trakt.tv/users/thechrisk/lists/alien-predator
        minimum_items: 3
        append_data:
          star: Star Wars Saga
          trek: Star Trek Universe
          xmen: X-Men Collection
        exclude:
          - marvel
          - rocky
    - pmm: seasonal
      template_variables:
        emoji: ""
        schedule_independence: range(06/28-07/05)
        schedule_halloween: range(09/15-10/31)
        exclude:
          - christmas
          - halloween

    overlay_path:
      - schedule: weekly(monday)
      - remove_overlays: false
      - folder: config/overlays/
        template_variables:
          vertical_offset: 15
          vertical_align: top

    operations:
      schedule: weekly(tuesday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: mdb

#4K MOVIES CONFIG
  4K Movies:
    overlay_path:
      - schedule: weekly(monday)
      - remove_overlays: false
      - folder: config/overlays
        template_variables:
          vertical_offset: 15
          vertical_align: top
      - pmm: resolution

    operations:
      schedule: weekly(tuesday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: mdb

#CHILDREN'S MOVIES CONFIG
  Movies - Family:
    metadata_path:
    - folder: config/Kids/
    - pmm: tautulli
      template_variables:
        use_watched: false
        
    overlay_path:
    - schedule: weekly(friday)
    - remove_overlays: false
    - folder: config/overlays/
      template_variables:
        vertical_offset: 15
        vertical_align: top

    operations:
      schedule: weekly(friday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: mdb

#TV SHOWS CONFIG
  TV Shows:
    metadata_path:
    - folder: config/Shows/

    overlay_path:
    - remove_overlays: false
    - folder: config/overlays/
      template_variables:
        vertical_offset: 15
        vertical_align: top

    operations:
      schedule: weekly(monday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: mdb

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 1
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users: