libraries:
  Movies:
    metadata_path:
    - folder: config/Movies/
    overlay_path:
    - remove_overlays: false
    - folder: config/overlays/
    - git: PMM/overlays/streaming
      template_variables:
        vertical_offset: 15
        vertical_align: top
    operations:
      mass_genre_update: tmdb                   
  Kids Movies:
    metadata_path:
    - folder: config/Kids/
    overlay_path:
    - remove_overlays: false
    - folder: config/overlays/
    - git: PMM/overlays/streaming
      template_variables:
        vertical_offset: 15
        vertical_align: top
    operations:
      mass_genre_update: tmdb
  TV Shows:
    metadata_path:
    - folder: config/Shows/
    overlay_path:
    - remove_overlays: false
    - folder: config/overlays/
    - git: PMM/overlays/streaming
      template_variables:
        vertical_offset: 15
        vertical_align: top
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: false
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
webhooks:
  error: 
  version: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
plex:
  url: http://10.252.20.14:32400
  token: uTM2jyeu_RGx8seCjE36
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:
  apikey: 8b5834c3a5033a8f564d64ec32c4345a
  language: en
  cache_expiration: 60
  region:
tautulli:
  url: http://10.252.20.15:8181
  apikey: f92ee82df1ac4e769d6cea47f7973642
#omdb:
  #apikey: ########
  #cache_expiration: 60
mdblist:
  apikey: ctdc8wn70taulk81l6blktmv2
  cache_expiration: 60
notifiarr:
  apikey: 941b4d0d-6611-4ce6-aef1-9d383c66f308 
radarr:
  url: http://10.252.55.12:7878
  token: 141b3719f3db4d75bcc058abef96f62e
  add_missing: false
  add_existing: false
  root_folder_path: /nfs/Movies
  monitor: true
  availability: announced
  quality_profile: HD-1080p
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false
sonarr:
  url: http://10.252.55.12:8989
  token: a3d46c53557d4a16b6bc43df3f7cbf72
  add_missing: false
  add_existing: false
  root_folder_path: /nfs/Shows
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
trakt:
  client_id: 41ae845fe03a7c0d12d933b92c64696ffba9db232549cd7fc658fb53ffe96367
  client_secret: ca8c7aac89ebb5d006a06085b4a41eac00827532d48b43c260419f9c9ce32497
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token: c42d1275fc0b48dcff2dab599621f0a71b6d12bb22e8078454334da47a451fc2
    token_type: Bearer
    expires_in: 7889237
    refresh_token: b7049a5110542978215f6d1f5e58244ae22c751de5856108c2c89debbb9bb7b2
    scope: public
    created_at: 1657054228
