libraries:
#MOVIE LIBRARY CONFIG FOR SCHEDULED COLLECTIONS TO BE DELETED WHEN OUT OF SEASON
  Scheduled:
    library_name: Movies
    report_path: config/missing/Scheduled_report.yml
    template_variables:
      use_separator: false
    metadata_path:
    - file: config/Scheduled/oscars.yml
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - file: config/Scheduled/golden.yml
      template_variables:
        use_year_collections: false
    - file: config/Scheduled/choice.yml
      template_variables:
        use_year_collections: false
    - file: config/Scheduled/Holiday.yml
    settings:
      delete_not_scheduled: true
      asset_directory: config/assets
 
 #MAIN MOVIE LIBRARY CONFIG
  Movies:
    report_path: config/missing/Movies_report.yml
    template_variables:
      use_separator: false
    metadata_path:
    - folder: config/Movies/
    - pmm: imdb
      template_variables:
        use_lowest: false
        order_top: 2
        order_popular: 2
    - pmm: trakt
      template_variables:
        use_collected: false
        use_recommended: false
        order_popular: 3
        order_trending: 3
        order_watched: 3
    - pmm: tautulli
      template_variables:
        use_watched: false
        list_days: 30
        list_size: 30
        summary_popular: A collection of the most watched movies on this Plex server.
        order_popular: 1
    - pmm: genre
      template_variables:
        sort_by: title.asc
        exclude:
        - Horror
        - War
        - Western
        - Spy
        - Sport
        - Musical
        - Indie
        - Biopic
      minimum_items: 10
    - pmm: decade
      template_variables:
        exclude:
          - 1960
        limit: 100
        limit_1970: 25
        summary_format: Top <<limit>> movies of the <<key>>s. Sorted by critic rating.
        summary_1970: Top <<limit_1970>> movies of the <<key>>s. Sorted by critic rating.
        minimum_items: 25
    - pmm: universe
      template_variables:
        trakt_list_mcu: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe
        trakt_list_dcu: https://trakt.tv/users/lampshadetricky/lists/dc-extended-universe
        trakt_list_trek: https://trakt.tv/users/thechrisk/lists/star-trek
        trakt_list_avp: https://trakt.tv/users/thechrisk/lists/alien-predator
        minimum_items: 3
        append_data:
          star: Star Wars Saga
          trek: Star Trek Universe
          xmen: X-Men Collection
        exclude:
          - marvel
          - rocky
        collection_section: "106"
    - pmm: seasonal
      template_variables:
        emoji: ""
        schedule_independence: range(06/28-07/05)
        schedule_halloween: range(09/15-10/31)
        exclude:
          - christmas
          - halloween
   
    overlay_path:
      - schedule: weekly(tuesday)
      - remove_overlays: false
      - file: config/overlays/Top.yml

    operations:
      schedule: weekly(monday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: mdb

#4K MOVIES CONFIG
  4K Movies:
    report_path: config/missing/4K_Movies_report.yml
    overlay_path:
      - schedule: weekly(tuesday)
      - remove_overlays: false
      - file: config/overlays/Top.yml
      - pmm: resolution
      - pmm: ratings
        template_variables:
          rating1: audience
          rating1_image: imdb
          rating1_vertical_align: bottom
          rating1_horizontal_align: left
          rating1_back_radius: 20

    operations:
      schedule: weekly(monday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: mdb

#CHILDREN'S MOVIES CONFIG
  Family:
    library_name: Movies - Family
    report_path: config/missing/Kids_Movies_report.yml
    metadata_path:
    #- folder: config/Kids/
    - pmm: tautulli
      template_variables:
        use_watched: false
        
    overlay_path:
    - schedule: weekly(friday)
    - remove_overlays: false
    - file: config/overlays/Top.yml

    operations:
      schedule: weekly(friday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: mdb

#TV SHOWS CONFIG
  TV Shows:
    report_path: config/missing/Shows_report.yml
    metadata_path:
    - folder: config/Shows/
    - file: config/Scheduled/emmy.yml
      template_variables:
        data:
          starting: current_year-1
          ending: current_year
    settings:
      delete_not_scheduled: true
      asset_directory: config/assets

    overlay_path:
    - remove_overlays: false
    - file: config/overlays/Top.yml

    operations:
      schedule: weekly(monday)
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: mdb

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 1
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: true
  show_unconfigured: true
  playlist_exclude_users: